// Base de datos en memoria - Maquinaria de Minería
const maquinaria = [
  {
    id: 1,
    nombre: "Excavadora Hidráulica CAT 390F",
    categoria: "Excavación",
    marca: "Caterpillar",
    modelo: "390F",
    año: 2022,
    capacidad: "90 toneladas",
    potencia: "575 HP",
    descripcion: "Excavadora de gran tonelaje ideal para minería a cielo abierto. Motor diesel de alta eficiencia con sistema hidráulico avanzado.",
    estado: "Disponible",
    precio_arriendo_dia: 4200000,
    imagen: "https://s7d2.scene7.com/is/image/Caterpillar/C10124150"
  },
  {
    id: 2,
    nombre: "Camión Minero Komatsu 930E",
    categoria: "Transporte",
    marca: "Komatsu",
    modelo: "930E",
    año: 2021,
    capacidad: "290 toneladas",
    potencia: "2700 HP",
    descripcion: "Camión de acarreo eléctrico de ultra gran capacidad. Transmisión eléctrica AC para máxima productividad en minas de gran escala.",
    estado: "En uso",
    precio_arriendo_dia: 8000000,
    imagen: "https://www.guiaminera.cl/wp-content/uploads/2022/06/Komatsu-930E-at-Los-Bronces-mine_06.02.2022.png"
  },
  {
    id: 3,
    nombre: "Perforadora Rotativa Atlas Copco DM45",
    categoria: "Perforación",
    marca: "Atlas Copco",
    modelo: "DM45",
    año: 2023,
    capacidad: "Diámetro 152-311mm",
    potencia: "450 HP",
    descripcion: "Perforadora rotaria de alto rendimiento para minería superficial. Sistema de control automático de presión y velocidad.",
    estado: "Disponible",
    precio_arriendo_dia: 3800000,
    imagen: "https://epiroc.scene7.com/is/image/epiroc/reverse+DM45-2?$landscape1600$"
  },
  {
    id: 4,
    nombre: "Motoniveladora Komatsu GD825A",
    categoria: "Nivelación",
    marca: "Komatsu",
    modelo: "GD825A",
    año: 2020,
    capacidad: "35 toneladas",
    potencia: "310 HP",
    descripcion: "Motoniveladora de alta capacidad para mantenimiento y construcción de caminos mineros. Hoja de 6.7 metros de ancho.",
    estado: "Mantenimiento",
    precio_arriendo_dia: 2100000,
    imagen: "https://www.lectura-specs.es/models/renamed/orig/motoniveladoras-gd825a-2-komatsu(1).jpg"
  },
  {
    id: 5,
    nombre: "Pala Cargadora Liebherr L586",
    categoria: "Carga",
    marca: "Liebherr",
    modelo: "L586",
    año: 2022,
    capacidad: "Cucharón 6.5 m³",
    potencia: "380 HP",
    descripcion: "Cargadora de ruedas de gran potencia para operaciones mineras. Transmisión hidrostática con control automático de tracción.",
    estado: "Disponible",
    precio_arriendo_dia: 3200000,
    imagen: "https://assets-cdn.liebherr.com/versions/408f6b9b-3b19-45c2-b602-468c62af470c/w-1280_h-1280_f-webp/L586_XPower_G6_10_2022.webp"
  },
  {
    id: 6,
    nombre: "Bulldozer CAT D11T",
    categoria: "Empuje",
    marca: "Caterpillar",
    modelo: "D11T",
    año: 2021,
    capacidad: "104 toneladas",
    potencia: "850 HP",
    descripcion: "El bulldozer más grande de Caterpillar. Ideal para remociones masivas de material estéril en minería de gran escala.",
    estado: "En uso",
    precio_arriendo_dia: 5500000,
    imagen: "https://s7d2.scene7.com/is/image/Caterpillar/CM20221201-09744-f107a"
  },
  {
    id: 7,
    nombre: "Compactadora Bomag BW 226 DH-5",
    categoria: "Compactación",
    marca: "Bomag",
    modelo: "BW 226 DH-5",
    año: 2023,
    capacidad: "19 toneladas",
    potencia: "220 HP",
    descripcion: "Rodillo vibratorio para compactación de caminos y plataformas mineras. Sistema ECONOMIZER para optimización de pasadas.",
    estado: "Disponible",
    precio_arriendo_dia: 1800000,
    imagen: "https://khsamgwebpro.blob.core.windows.net/wp-content/uploads/2022/11/22160606/BW226DH-5_contenido.jpg"
  },
  {
    id: 8,
    nombre: "Grúa Liebherr LTM 1500-8.1",
    categoria: "Izaje",
    marca: "Liebherr",
    modelo: "LTM 1500-8.1",
    año: 2020,
    capacidad: "500 toneladas",
    potencia: "680 HP",
    descripcion: "Grúa móvil todo terreno de 500 toneladas para montaje de equipos y estructuras en faenas mineras.",
    estado: "Disponible",
    precio_arriendo_dia: 1200000,
    imagen: "https://www.lectura-specs.es/models/renamed/orig/gruas-todo-terreno-ltm-1500-16x8x12--liebherr(4).jpg"
  },
  {
    id: 9,
    nombre: "Camión Minero Subterráneo Epiroc Minetruck MT65 S",
    categoria: "Transporte Subterráneo",
    marca: "Epiroc",
    modelo: "MT65 S",
    año: 2023,
    capacidad: "65 toneladas",
    potencia: "770 HP",
    descripcion: "Camión articulado de interior mina, uno de los más grandes del mundo en su categoría. Diseñado para operaciones subterráneas de gran volumen con sistema de control RCS y motor Tier 4 Final.",
    estado: "Disponible",
    precio_arriendo_dia: 6800000,
    imagen: "https://epiroc.scene7.com/is/image/epiroc/Minetruck+MT65+S_Comm_0078?$landscape1600$"
  },
  {
    id: 10,
    nombre: "Cargador Subterráneo Sandvik Toro LH621i",
    categoria: "Carga Subterránea",
    marca: "Sandvik",
    modelo: "LH621i",
    año: 2023,
    capacidad: "21 toneladas",
    potencia: "470 HP",
    descripcion: "Cargador LHD para desarrollo rápido de minas y producción subterránea a gran escala. Geometría de brazo inteligente para llenado rápido del cucharón y alta velocidad en rampa.",
    estado: "Disponible",
    precio_arriendo_dia: 4500000,
    imagen: "https://www.mining.sandvik/cdn-cgi/image/w=1200,h=630,quality=90,fit=cover,format=avif/siteassets/images/loaders/diesel-loaders/lh621i/lh621i-003.jpg?v=1698044822"
  },
  {
    id: 11,
    nombre: "Perforadora Rotativa Sandvik DR416i",
    categoria: "Perforación",
    marca: "Sandvik",
    modelo: "DR416i",
    año: 2023,
    capacidad: "Diámetro 270-406mm",
    potencia: "1400 HP",
    descripcion: "La perforadora rotativa de mayor diámetro de Sandvik, sobre orugas, diseñada para minería de cobre y mineral de hierro. Capacidad de una sola pasada de 21 metros y sistema de control inteligente SICA.",
    estado: "Disponible",
    precio_arriendo_dia: 5200000,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgpKmedngmBAkidl2PImP3KKjeN39iMrkkHgyrrm_ghj-DSE1VFOTA-ako&s=10"
  },
  {
    id: 12,
    nombre: "Camión Minero Subterráneo Epiroc Minetruck MT42",
    categoria: "Transporte Subterráneo",
    marca: "Epiroc",
    modelo: "MT42",
    año: 2022,
    capacidad: "42 toneladas",
    potencia: "550 HP",
    descripcion: "Camión articulado de alta velocidad para transporte subterráneo, minería y construcción. Suspensión en eje delantero y motor Cummins QSX15 con bajas emisiones Tier 4 Final.",
    estado: "En uso",
    precio_arriendo_dia: 5400000,
    imagen: "https://epiroc.scene7.com/is/image/epiroc/Minetruck+MT42+SG+comm+2?$landscape1600$"
  },
  {
    id: 13,
    nombre: "Camión Aljibe CAT 777G Water Solutions",
    categoria: "Riego de Caminos",
    marca: "Caterpillar",
    modelo: "777G Water Solutions",
    año: 2022,
    capacidad: "65.000 litros",
    potencia: "938 HP",
    descripcion: "Camión aljibe sobre chasis 777G para riego y supresión de polvo en caminos mineros. Sistema de aspersión de ancho variable y bombas de alto caudal para máxima cobertura.",
    estado: "Disponible",
    precio_arriendo_dia: 4100000,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCnTbvT2sigTi7r3H_H4BxoJJQwLKclDQ6jGwZm84wsrnyDJo3PLCZz8E&s=10"
  },
  {
    id: 14,
    nombre: "Chancadora Móvil de Mandíbula Metso Lokotrack LT120",
    categoria: "Chancado",
    marca: "Metso",
    modelo: "Lokotrack LT120",
    año: 2022,
    capacidad: "Hasta 350 ton/h",
    potencia: "350 HP",
    descripcion: "Planta chancadora móvil sobre orugas con chancador de mandíbula. Ideal para reducción primaria de mineral y estéril directamente en el frente de la faena, reduciendo costos de acarreo.",
    estado: "Disponible",
    precio_arriendo_dia: 4700000,
    imagen: "https://api.sitsa.com.mx/media/img/gallery/brands/Metso5.webp"
  },
  {
    id: 15,
    nombre: "Excavadora Hidráulica Komatsu PC2000",
    categoria: "Excavación",
    marca: "Komatsu",
    modelo: "PC2000-11",
    año: 2022,
    capacidad: "124 toneladas",
    potencia: "979 HP",
    descripcion: "Excavadora hidráulica de gran tonelaje para carguío directo en minería a cielo abierto. Cucharón de hasta 13 m³ y sistema de control electrónico de potencia para máxima eficiencia de combustible.",
    estado: "Disponible",
    precio_arriendo_dia: 5900000,
    imagen: "https://www.lectura-specs.es/models/renamed/orig/excavadoras-de-orugas-pc2000-11-komatsu.jpeg"
  },
  {
    id: 16,
    nombre: "Camión Minero Liebherr T 284",
    categoria: "Transporte",
    marca: "Liebherr",
    modelo: "T 284",
    año: 2021,
    capacidad: "363 toneladas",
    potencia: "3650 HP",
    descripcion: "Camión de acarreo de ultra clase con transmisión eléctrica AC Litronic Plus. Uno de los camiones mineros más grandes del mundo, diseñado para minas de cobre y carbón de gran escala.",
    estado: "En uso",
    precio_arriendo_dia: 9500000,
    imagen: "https://assets-cdn.liebherr.com/versions/d7c1d9a8-6866-44b3-9188-1e0185d1c76e/w-1280_h-1280_f-webp/liebherr-T284.webp"
  },
  {
    id: 17,
    nombre: "Bulldozer Komatsu D375A",
    categoria: "Empuje",
    marca: "Komatsu",
    modelo: "D375A-8",
    año: 2022,
    capacidad: "55 toneladas",
    potencia: "610 HP",
    descripcion: "Bulldozer de gran tonelaje para movimiento de material estéril y construcción de plataformas mineras. Hoja semi-U de gran capacidad y sistema de control de transmisión electrónico.",
    estado: "Disponible",
    precio_arriendo_dia: 3900000,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqWyeR574B3yOoJcWEU_IpXMjgCmYwrppqpPF9xUvNyeP7GRsTjCcb5LCs&s=10"
  }
];

const categorias = [
  "Excavación",
  "Transporte",
  "Perforación",
  "Nivelación",
  "Carga",
  "Empuje",
  "Compactación",
  "Izaje",
  "Transporte Subterráneo",
  "Carga Subterránea",
  "Riego de Caminos",
  "Chancado"
];

module.exports = { maquinaria, categorias };